#!/usr/bin/env python3
import time
while True:
  try:
    input("Press enter to continue and ctrl+c to exit the stopwatch.")
    start_time=time.time()
    print("Stopwatch has started.")
    while True:
      print("Time Elapsed:", round(time.time()-start_time,0), 'secs', end='\n')
      time.sleep(1)
  except KeyboardInterrupt:
    print("\nTimer has stopped")
    end_time=time.time()
    print("Total Time Elapsed:", round(end_time-start_time, 2), 'secs')
    break
